Fix unit test err due to missing dep on injection
    Adyen\Payment\Tests\Helper\DataTest::testFormatAmount
ArgumentCountError: Too few arguments to function Adyen\Payment\Helper\Data::__construct(), 9 passed